INSERT INTO `cs6400_summer18_team010`.`User` (`Username`, `Name`, `Password`) VALUES ('muni', 'muni', 'muni');
INSERT INTO `cs6400_summer18_team010`.`User` (`Username`, `Name`, `Password`) VALUES ('comp', 'comp', 'comp');
INSERT INTO `cs6400_summer18_team010`.`User` (`Username`, `Name`, `Password`) VALUES ('gov', 'gov', 'gov');
INSERT INTO `cs6400_summer18_team010`.`User` (`Username`, `Name`, `Password`) VALUES ('ind', 'ind', 'ind');
INSERT INTO `cs6400_summer18_team010`.`GovAgencies` (`Username`, `AgencyNameLocalOffice`) VALUES ('gov', 'agencyName');
INSERT INTO `cs6400_summer18_team010`.`Individuals` (`Username`, `JobTitle`, `DateHired`) VALUES ('ind', 'jobTitle', '2018/7/18');
INSERT INTO `cs6400_summer18_team010`.`Companies` (`Username`, `Location`, `NumberofEmployees`) VALUES ('comp', 'location', '100');
INSERT INTO `cs6400_summer18_team010`.`Municipalities` (`Username`, `Category`) VALUES ('muni', 'category');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('1', 'Transportation');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('2', 'Communications');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('3', 'Public Works and Engineering');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('4', 'Firefighting');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('5', 'Emergency Management');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('6', 'Mass Care, Emergency Assistance, Housing, and Human Services');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('7', 'Logistics Management and Resource Support');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('8', 'Public Health and Medical Services');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('9', 'Search and Rescue');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('10', 'Oil and Hazardous Materials Response');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('11', 'Agriculture and Natural Resources');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('12', 'Energy');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('13', 'Public Safety and Security');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('14', 'Long-Term Community Recovery');
INSERT INTO `cs6400_summer18_team010`.`ESF` (`Number`, `Description`) VALUES ('15', 'External Affairs');
INSERT INTO `cs6400_summer18_team010`.`TimeUnit` (`Name`) VALUES ('Hour');
INSERT INTO `cs6400_summer18_team010`.`TimeUnit` (`Name`) VALUES ('Day');
INSERT INTO `cs6400_summer18_team010`.`TimeUnit` (`Name`) VALUES ('Week');
INSERT INTO `cs6400_summer18_team010`.`Declarations` (`Abbreviation`, `Name`) VALUES ('MD', 'Major Disaster');
INSERT INTO `cs6400_summer18_team010`.`Declarations` (`Abbreviation`, `Name`) VALUES ('ED', 'Emergency');
INSERT INTO `cs6400_summer18_team010`.`Declarations` (`Abbreviation`, `Name`) VALUES ('FM', 'Fire Management Assistance');
INSERT INTO `cs6400_summer18_team010`.`Declarations` (`Abbreviation`, `Name`) VALUES ('FS', 'Fire Suppression Authorization');

